#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
## me executuable "
EXEC="${HERE}/usr/bin/jme" 
export LD_LIBRARY_PATH="${HERE}/usr/lib64"
if [ ! -d "${HOME}/.jasspa" ]; then 
    mkdir "${HOME}/.jasspa"
fi    
if [ ! -f  "${HOME}/.jasspa/lsdxenus.edf" ]; then
    cp ${HERE}/usr/share/spelling/*f ~/.jasspa/
    cp ${HERE}/usr/share/spelling/README.txt ~/.jasspa/README-spelling.txt
fi
if [ "$1" == "-n" ]; then
    TERM=xterm $EXEC "${@}"
else
    if [ -n $DISPLAY ]; then
        #if [ ! -d ~/.jasspa/ubuntu-fonts ]; then
        #    cp -r "${HERE}/usr/share/ubuntu-fonts" ~/.jasspa/fonts
        #fi
        #if [ command -v xlsfonts &> /dev/null ] && [ command -v xset &> /dev/null ]; then
        #    res=`xlsfonts | grep -E "ubuntu mono-bold.+17"`
        #    if [ ! "$res" != "" ]; then
        #        xset +fp ~/.jasspa/fonts/
        #        xset fp rehash
        #    fi
        #fi
        $EXEC "${@}"
    else
        TERM=xterm $EXEC -n "${0}"
    fi
fi    

