/* XPM */
static char * me_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	c #C0C0C0C0C0C0",
".	s iconColor1	m black	c black",
"X	c #00000000FFFF",
"o	s none	m none	c none",
"O	s iconColor6	m white	c yellow",
"+	c #FFFF00000000",
/* pixels */
"                                                ",
"                                                ",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..",
"o.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.o",
"oo.                                          .oo",
"oo.                                          .oo",
"ooo..........................................ooo",
"ooo..........................................ooo",
"oooo.........................................ooo",
"oooo...............OOOOOOOOOO...............oooo",
"ooooo............OOOOOOOOOOOOOO.............oooo",
"ooooo...........OOOOOOOOOOOOOOOOO..........ooooo",
"oooooo.........OOOOOOOOOOOOOOOOOOO.........ooooo",
"oooooo........OOOOOOOO....OOOOOOOO........oooooo",
"ooooooo.......OOOOOOO......OOOOOOOO.......oooooo",
"oooooooo.....OOOOOOO........OOOOOOO......ooooooo",
"oooooooo....OOOOOOO..........OOOOOO......ooooooo",
"oooooooo....OOOOOO............OOOOOO....oooooooo",
"ooooooooo...OOOOOO............OOOOOO...ooooooooo",
"ooooooooo...OOOOOOOOOOOOOOOOOOOOOOOO...ooooooooo",
"oooooooooo..OOOOOOOOOOOOOOOOOOOOOOOO..oooooooooo",
"ooooooooooo.OOOOOOOOOOOOOOOOOOOOOOOO..oooooooooo",
"ooooooooooo.OOOOOOOOOOOOOOOOOOOOOOOO..oooooooooo",
"ooooooooooo.OOOOOOOOOOOOOOOOOOOOOOOO.ooooooooooo",
"ooooooooooo.OOOOOO...................ooooooooooo",
"ooooooooooo.OOOOOO..................oooooooooooo",
"oooooooooooo.OOOOOO.................oooooooooooo",
"oooooooooooo.OOOOOOO...............ooooooooooooo",
"ooooooooooooo.OOOOOOO........OOOO..ooooooooooooo",
"ooooooooooooo.OOOOOOOO......OOOOOO..oooooooooooo",
"oooooooooooooo.OOOOOOOOOOOOOOOOOOOOO.ooooooooooo",
"ooooooooooooooo..OOOOOOOOOOOOOOOOOO.oooooooooooo",
"oooooooooooooooo..OOOOOOOOOOOOOOOO.ooooooooooooo",
"oooooooooooooooo....OOOOOOOOOOO...oooooooooooooo",
"oooooooooooooooo.................ooooooooooooooo",
"ooooooooooooooooo...............oooooooooooooooo",
"ooooooooooooooooo.            .ooooooooooooooooo",
"oooooooooooooooooo.++++++++++.oooooooooooooooooo",
"ooooooooooooooooooo.+++++++++.oooooooooooooooooo",
"ooooooooooooooooooo.++++++++.ooooooooooooooooooo",
"oooooooooooooooooooo.+++++++.ooooooooooooooooooo",
"oooooooooooooooooooo.++++++.oooooooooooooooooooo",
"ooooooooooooooooooooo.+++++.oooooooooooooooooooo",
"ooooooooooooooooooooo.++++.ooooooooooooooooooooo",
"oooooooooooooooooooooo.+++.ooooooooooooooooooooo",
"ooooooooooooooooooooooo...oooooooooooooooooooooo"};
