/* XPM */
static char * me_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 0 0",
/* colors */
" 	c #C0C0C0C0C0C0",
".	s iconColor1	m black	c black",
"X	c #00000000FFFF",
"o	s none	m none	c none",
"O	s iconColor6	m white	c yellow",
"+	c #FFFF00000000",
/* pixels */
"                                ",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"o.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.o",
"o.                            .o",
"oo............................oo",
"oo............................oo",
"ooo..........OOOOOO..........ooo",
"ooo........OOOOOOOOOO........ooo",
"oooo......OOOOOOOOOOOO......oooo",
"oooo.....OOOOO....OOOOO.....oooo",
"ooooo....OOOO......OOOO....ooooo",
"ooooo...OOOO........OOO....ooooo",
"oooooo..OOOO........OOOO..oooooo",
"oooooo..OOOOOOOOOOOOOOOO..oooooo",
"ooooooo.OOOOOOOOOOOOOOOO.ooooooo",
"ooooooo.OOOOOOOOOOOOOOOO.ooooooo",
"ooooooo.OOOO............oooooooo",
"ooooooo.OOOO............oooooooo",
"oooooooo.OOOO..........ooooooooo",
"oooooooo.OOOOO.....OOO..oooooooo",
"ooooooooo.OOOOOOOOOOOOOOoooooooo",
"oooooooooo.OOOOOOOOOOOO.oooooooo",
"ooooooooooo..OOOOOOO...ooooooooo",
"ooooooooooo..........ooooooooooo",
"oooooooooooo.      .oooooooooooo",
"oooooooooooo.++++++.oooooooooooo",
"ooooooooooooo.++++.ooooooooooooo",
"ooooooooooooo.++++.ooooooooooooo",
"oooooooooooooo.++.oooooooooooooo",
"oooooooooooooo.++.oooooooooooooo",
"ooooooooooooooo  ooooooooooooooo"};
