name: Binaries Windows (linux-mingw-gcc)

on:
  workflow_dispatch:
    branches: [ master ]

env: 
    VERSION: "091224b2"

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
     
    - name: developer library installs
      run: |
        sudo apt install build-essential mingw-w64 gcc-mingw-w64-i686 
        sudo apt install libz-mingw-w64 libz-mingw-w64-dev
        sudo apt install desktop-file-utils
        export VRS=`grep -E 'meYEAR|meMONTH|meDAY' src/evers.h | head -n 3 | awk '{ print $3 }' | paste -sd '-' | sed 's/[-"]//g'`
        echo "VRS=$VRS" >> $GITHUB_ENV

    - name: make bfs binary
      run:  make -f win32mingw.gmk bfs/bin

    - name: make mec binary       
      run:  make -f win32mingw.gmk mec

    - name: make mew binary       
      run:  make -f win32mingw.gmk mew

    - name: make mecb binary
      run:  |
        make -f win32mingw.gmk mecb
    
    - name: make mecw binary
      run:  make -f win32mingw.gmk mewb
    
    - name: make mecw binary
      run:  make -f win32mingw.gmk bfs/exe
    
    - name: make brew package
      run:  | 
        make -f win32mingw.gmk brew
        rm -rf brew-*/

    - name: make scope package
      run: |
        make -f win32mingw.gmk scoop
        rm -rf mecw-scoop-*/
        
    - name: Download zlib1.dll
      run: |
        wget  https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-16.0.0-10.0.0-ucrt-r5/winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.zip
        unzip -q winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.zip
        cp mingw32/bin/zlib1.dll .
        wget https://github.com/madler/zlib/raw/develop/LICENSE -O zlib-LICENSE.txt

    - name: Make release
      run: |
        mkdir MicroEmacs09-${VRS}-Windows
        mkdir MicroEmacs09-${VRS}-Windows/bin
        #cp zlib1.dll MicroEmacs09-${VRS}-Windows/bin/
        #cp zlib-LICENSE.txt MicroEmacs09-${VRS}-Windows/bin/
        cp bfs/bfs.exe MicroEmacs09-${VRS}-Windows/bin/
        cp src/.win32mingw-release-mew/mew32.exe MicroEmacs09-${VRS}-Windows/bin/
        cp src/.win32mingw-release-mec/mec32.exe  MicroEmacs09-${VRS}-Windows/bin/
        cp windows-*me*.exe MicroEmacs09-${VRS}-Windows/bin/
        cp license.txt MicroEmacs09-${VRS}-Windows/
        cp COPYING MicroEmacs09-${VRS}-Windows/
        cp README-standalone.md MicroEmacs09-${VRS}-Windows/
        cd jasspa 
        zip macros.zip macros/*
        cd ..
        cp jasspa/macros.zip MicroEmacs09-${VRS}-Windows/

    - name: Make mecb release
      run: |
        mkdir MicroEmacs09-${VRS}-Windows-mecb
        mkdir MicroEmacs09-${VRS}-Windows-mecb/bin
        #cp zlib1.dll MicroEmacs09-${VRS}-Windows-mecb/bin/
        #cp zlib-LICENSE.txt MicroEmacs09-${VRS}-Windows-mecb/bin/
        cp bfs/bfs.exe MicroEmacs09-${VRS}-Windows-mecb/bin/
        cp windows-*-mecb.exe MicroEmacs09-${VRS}-Windows-mecb/bin/
        cp license.txt MicroEmacs09-${VRS}-Windows-mecb/
        cp COPYING MicroEmacs09-${VRS}-Windows-mecb/
        cp README-standalone.md MicroEmacs09-${VRS}-Windows-mecb/

    - name: Make mewb release
      run: |
        mkdir MicroEmacs09-${VRS}-Windows-mewb
        mkdir MicroEmacs09-${VRS}-Windows-mewb/bin
        #cp zlib1.dll MicroEmacs09-${VRS}-Windows-mewb/bin/
        #cp zlib-LICENSE.txt MicroEmacs09-${VRS}-Windows-mewb/bin/
        cp bfs/bfs.exe MicroEmacs09-${VRS}-Windows-mewb/bin/
        cp windows-*-mewb.exe MicroEmacs09-${VRS}-Windows-mewb/bin/
        cp license.txt MicroEmacs09-${VRS}-Windows-mewb/
        cp COPYING MicroEmacs09-${VRS}-Windows-mewb/
        cp README-standalone.md MicroEmacs09-${VRS}-Windows-mewb/

    - name: Upload Windows Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VRS }}-Windows
        path: MicroEmacs09-${{ env.VRS }}-Windows
    

    - name: Upload Windows mecb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VRS }}-Windows-mecb
        path: MicroEmacs09-${{ env.VRS }}-Windows-mecb
    
    - name: Upload Windows mewb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VRS }}-Windows-mewb
        path: MicroEmacs09-${{ env.VRS }}-Windows-mewb

    - name: Combined Release
      run: |
        make -f win32mingw.gmk release app=mecb
        make -f win32mingw.gmk release app=mewb
        export DIR=`ls windows-*-mecb.exe | sed 's/-mecb.exe//'`
        echo $DIR
    - name: Upload Ubuntu Combined Release
      uses: actions/upload-artifact@v4
      with: 
        name: Release-windows-10-intel
        path: windows-10-intel-*/

    - name: Upload Brew Package
      uses: actions/upload-artifact@v4
      with: 
        name: brew-windows
        path: brew-*

    - name: Upload Scoop Package
      uses: actions/upload-artifact@v4
      with: 
        name: scoop-windows
        path: scoop-*
