name: Binaries Windows-Msys2

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "091226b2"
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32, runs-on: 'windows-latest', subsystem: msys }
          - { sys: mingw64, runs-on: 'windows-latest', subsystem: msys }
          - { sys: ucrt64, runs-on: 'windows-latest', subsystem: msys }
          - { sys: mingw32, runs-on: 'windows-latest', subsystem: mingw }
          - { sys: mingw64, runs-on: 'windows-latest', subsystem: mingw }
          - { sys: ucrt64, runs-on: 'windows-latest', subsystem: mingw }
    name: ${{ matrix.subsystem }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false    
    - name: Setup MSYS2     
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{ matrix.sys }}
        install: >-
           curl
           git
           make
           unzip 
           zip
    - name: Install MSYS packages
      if: matrix.subsystem == 'msys'
      run: |
         pacman -S --noconfirm gcc ncurses ncurses-devel zlib zlib-devel
    - name: Install MinGW packages
      if: matrix.subsystem == 'mingw'
      run: |
         pacman -S --noconfirm mingw-w64-${{ matrix.sys }}-gcc mingw-w64-${{ matrix.sys }}-ncurses mingw-w64-${{ matrix.sys }}-zlib
    - name: compile bfs executable
      run: |
         gcc --version
         uname -a
         uname -m
         cd bfs
         make -f winmingwgcc.gmk
         ls -la
         cd ..

    - name: compile mec executable
      run: |
         cd src
         make -f winmingwgcc.mak BTYP=c all
         ls -la
         ./.${{ matrix.subsystem }}64-release-mec/mec32.exe -V
         cd ..
    - name: compile mew executable
      run: |
         cd src
         make -f winmingwgcc.mak BTYP=w all
         ls -la
         cd ..
    - name: create mecb executable
      run: |
         make -f winmingwgcc.gmk mecb
    - name: create mewb executable
      run: |
         make -f winmingwgcc.gmk mewb

    - name: create Release executable
      run: |
         make -f winmingwgcc.gmk release app=mecb
         make -f winmingwgcc.gmk release app=mewb
         ls
    
    - name: Upload Release
      uses: actions/upload-artifact@v6
      with: 
        name: Release-${{ matrix.subsystem }}-${{ matrix.sys }}-${{ env.VERSION }}
        path: windows-msys-microemacs*
