name: Binaries Windows-Msys2

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "091226b2"
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32, runs-on: 'windows-latest' }
          - { sys: mingw64, runs-on: 'windows-latest' }
          - { sys: ucrt64, runs-on: 'windows-latest' }
    name: run ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false    
    - name: Setup     
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
           curl
           git
           make
           zlib
           zlib-devel
           gcc
           ncurses
           ncurses-devel
    - name: compile bfs executable
      run: |
         gcc --version
         uname -a
         uname -m
         uname -s
         uname -o
         uname -r
         cd bfs
         make -f winmingwgcc.gmk
         ls -la
         cd ..

    - name: compile mec executable
      run: |
         cd src
         make -f winmingwgcc.mak BTYP=c all
         ls -la
         ./.winmingwgcc-release-mec/mec32.exe -V
         cd ..
    - name: compile mew executable
      run: |
         cd src
         make -f winmingwgcc.mak BTYP=w all
         ls -la
         pwd
         ls /c/*
         cd ..
         cygpath `pwd`
    - name: create mecb executable
      run: |
         make -f winmingwgcc.gmk mecb
    - name: create mewb executable
      run: |
         make -f winmingwgcc.gmk mecb

    - name: create Release executable
      run: |
         make -f winmingwgcc.gmk release app=mecb
         make -f winmingwgcc.gmk release app=mewb
         ls
    - name: Upload Msys Combined Release I
      uses: actions/upload-artifact@v6
      with: 
        name: winmingwgcc-${{ matrix.sys }}-${{ env.VERSION }}-windows
        path: me*b*exe
    
    - name: Upload Msys Combined Release II
      uses: actions/upload-artifact@v6
      with: 
        name: Release-winmingwgcc-${{ matrix.sys }}-${{ env.VERSION }}-windows
        path: *

    - name: Upload Msys64
      uses: actions/upload-artifact@v6
      with: 
        name: Release-${{ matrix.sys }}
        path: c:\msys64
    
