name: Binaries Windows-Msys2

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "091226b2"
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32, runs-on: 'windows-latest' }
          - { sys: mingw64, runs-on: 'windows-latest' }
          - { sys: ucrt64, runs-on: 'windows-latest' }
          - { sys: clang64, runs-on: 'windows-latest' }
          - { sys: clangarm64, runs-on: 'windows-11-arm' }
    name: run ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false    
    - name: Setup     
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
           curl
           git
           make
    - name: developer library installs
      run: |
        uname -a
        uname -m
        uname -s
        uname -o
        uname -r
        ls -l
        cd src
        make -f win32mingw.mak BTYP=c
        ls -la
        cd ../bfs
        make -f win32mingw.gmk
        ls -la
        cd ..
        
        pwd
    
