name: Testing MicroEmacs Installs

on:
  workflow_dispatch:
  push:
    branches: [ devel ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    name: Test on Linux
    steps:
      - uses: actions/checkout@v6
      - name: Install build dependencies
        run: |
          sudo apt-get update
      - name: Ckeck install mec (console)
        run: |
         bash -c "$(curl -fsSL https://github.com/mittelmark/microemacs/releases/latest/download/install.sh)"
         source ~/.bashrc ## for the current session update the PATH settings
         mecb -V

  macos:
    runs-on: macos-latest
    name: Test on macOS
    steps:
      - uses: actions/checkout@v6
      - name: Ckeck install mec (console)
        run: |
           bash -c "$(curl -fsSL https://github.com/mittelmark/microemacs/releases/latest/download/install.sh)"
           source ~/.bashrc ## for the current session update the PATH settings
           mecb -V
  windows-mingw:
    runs-on: windows-latest
    name: Test on Windows (MinGW64)
    steps:
      - uses: actions/checkout@v6
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: make unzip zip
      - name: Ckeck install mec (console)
        shell: msys2 {0}
        run: |
           bash -c "$(curl -fsSL https://github.com/mittelmark/microemacs/releases/latest/download/install.sh)"
           source ~/.bashrc ## for the current session update the PATH settings
           tail ~/.bashrc
           ~/.local/bin/mecb -V
  windows-pwsh:
    runs-on: windows-latest
    name: Test on Windows (Powershell)
    steps:
      - uses: actions/checkout@v6
      - name: Ckeck install mec (console)
        shell: pwsh
        run: |
           Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
           Invoke-RestMethod -Uri https://github.com/mittelmark/microemacs/releases/latest/download/install-windows.ps1 > install-windows.ps1
           @"
           y
           y
           y
           "@ | powershell.exe .\install-windows.ps1
           dir
           & C:\Users\runneradmin\AppData\Local\bin\mecb.exe -V
  cygwin-x64:
    runs-on: windows-latest
    name: Test on Cygwin (x86_64)
    steps:
      - uses: actions/checkout@v6
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v6
        with:
          packages: |
            make
          install-dir: C:\cygwin
          platform: x86_64
      - name: Check install mec (console)
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
           mkdir -p ~/.local/share/fonts
           bash -c "$(curl -fsSL https://github.com/mittelmark/microemacs/releases/latest/download/install.sh)"
           source ~/.bashrc ## for the current session update the PATH settings
           ~/.local/bin/mecb -V

  windows-winlibs:
    runs-on: windows-2022
    name: Test on Windows (mingw-ucrt)
    steps:
      - uses: actions/checkout@v6
      - name: Check install mec (console)
        shell: pwsh
        run: |
            Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
            Invoke-RestMethod -Uri https://github.com/mittelmark/microemacs/releases/latest/download/install-windows.ps1 | Invoke-Expression
            mecb -V
